version: 1
disable_existing_loggers: true

formatters:
    verbose:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(process)d:%(processName)s - %(funcName)s:%(lineno)d - %(message)s'
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    discord:
        format: '%(message)s'
    uvicorn_default:
        "()": uvicorn.logging.DefaultFormatter
        format: '%(asctime)s - %(levelprefix)s %(name)s - %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: uvicorn_default
        stream: ext://sys.stderr

    debug_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ./logs/debug.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

    error_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: verbose
        filename: ./logs/errors.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

    access_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./logs/access.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

    discord_handler:
        class: app.core.log_handlers.DiscordWebhookHandler
        level: INFO
        formatter: discord

root:
    level: NOTSET
    handlers: [console, debug_handler, error_handler, discord_handler]
    propagate: false

loggers:
    uvicorn:
        level: DEBUG
        handlers: [console, debug_handler, discord_handler]
        propagate: false

    uvicorn.error:
        level: ERROR
        handlers: [console, error_handler, discord_handler]
        propagate: false

    uvicorn.access:
        level: INFO
        handlers: [console, access_handler]
        propagate: false

    watchfiles:
        level: INFO
        handlers: [console]
        propagate: false