"""TZ aware datetimes

Revision ID: 1013b783c191
Revises: 1fafdb893dd5
Create Date: 2025-03-17 20:25:29.277164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1013b783c191'
down_revision: Union[str, None] = '1fafdb893dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ckey_link_token', 'expiration_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('donation', 'issue_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('donation', 'expiration_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('whitelist', 'expiration_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('whitelist_ban', 'expiration_time',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist_ban', 'expiration_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('whitelist', 'expiration_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('donation', 'expiration_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('donation', 'issue_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('ckey_link_token', 'expiration_time',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
